name: wasil_shopping
description: "A Flutter shopping app with product listing, cart, and Firebase
  authentication."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.11
  connectivity_plus: ^6.1.4
  crystal_navigation_bar: ^1.0.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.8
  get_it: ^8.0.0
  go_router: ^16.0.0
  http: ^1.2.2
  iconly: ^1.0.1
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
